
import properties from './definitions.js'

/**
 * @see {@link https://drafts.csswg.org/css-page-3/#page-property}
 */
const included = [
    '--*',
    'background',
    'background-attachment',
    'background-color',
    'background-image',
    'background-position',
    'background-repeat',
    'border',
    'border-bottom',
    'border-bottom-color',
    'border-bottom-style',
    'border-bottom-width',
    'border-color',
    'border-left',
    'border-left-color',
    'border-left-style',
    'border-left-width',
    'border-right',
    'border-right-color',
    'border-right-style',
    'border-right-width',
    'border-short-style',
    'border-top',
    'border-top-color',
    'border-top-style',
    'border-top-width',
    'border-width',
    'color',
    'counter-increment',
    'counter-reset',
    'direction',
    'font',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'height',
    'letter-spacing',
    'line-height',
    'margin',
    'margin-bottom',
    'margin-left',
    'margin-right',
    'margin-top',
    'max-height',
    'max-width',
    'min-height',
    'min-width',
    'outline',
    'outline-color',
    'outline-style',
    'outline-width',
    'padding',
    'padding-bottom',
    'padding-left',
    'padding-right',
    'padding-top',
    'quotes',
    'text-align',
    'text-decoration',
    'text-indent',
    'text-transform',
    'visibility',
    'white-space',
    'width',
    'word-spacing',
]
const entries = included.map(name => [name, properties[name]])

export default Object.fromEntries(entries)
