
const colorFunctionKeywords = {
    hsl: 'h | s | l | alpha',
    hsla: 'h | s | l | alpha',
    hwb: 'h | w | b | alpha',
    ictcp: 'i | ct | cp | alpha',
    jzazbz: 'jz | az | bz | alpha',
    jzczhz: 'jz | cz | hz | alpha',
    lab: 'l | a | b | alpha',
    lch: 'l | c | h | alpha',
    oklab: 'l | a | b | alpha',
    oklch: 'l | c | h | alpha',
    rgb: 'r | g | b | alpha',
    rgba: 'r | g | b | alpha',
}

const colorSpaceKeywords = {
    '<dashed-ident>': '<ident> | alpha',
    '<predefined-rgb>': 'r | g | b | alpha',
    '<xyz-space>': 'x | y | z | alpha',
}

const colorSpaces = Object.keys(colorSpaceKeywords)

/**
 * @see {@link https://drafts.csswg.org/css-color-4/#typedef-deprecated-color}
 */
const deprecated = [
    ['ActiveBorder', 'ButtonBorder'],
    ['ActiveCaption', 'Canvas'],
    ['AppWorkspace', 'Canvas'],
    ['Background', 'Canvas'],
    ['ButtonHighlight', 'ButtonFace'],
    ['ButtonShadow', 'ButtonFace'],
    ['CaptionText', 'CanvasText'],
    ['InactiveBorder', 'ButtonBorder'],
    ['InactiveCaption', 'Canvas'],
    ['InactiveCaptionText', 'GrayText'],
    ['InfoBackground', 'Canvas'],
    ['InfoText', 'CanvasText'],
    ['Menu', 'Canvas'],
    ['MenuText', 'CanvasText'],
    ['Scrollbar', 'Canvas'],
    ['ThreeDDarkShadow', 'ButtonBorder'],
    ['ThreeDFace', 'ButtonFace'],
    ['ThreeDHighlight', 'ButtonBorder'],
    ['ThreeDLightShadow', 'ButtonBorder'],
    ['ThreeDShadow', 'ButtonBorder'],
    ['Window', 'Canvas'],
    ['WindowFrame', 'ButtonBorder'],
    ['WindowText', 'CanvasText'],
]

/**
 * @see {@link https://drafts.csswg.org/css-color-4/#typedef-named-color}
 */
const named = [
    'aliceblue',
    'antiquewhite',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'black',
    'blanchedalmond',
    'blue',
    'blueviolet',
    'brown',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkgreen',
    'darkgrey',
    'darkkhaki',
    'darkmagenta',
    'darkolivegreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkseagreen',
    'darkslateblue',
    'darkslategray',
    'darkslategrey',
    'darkturquoise',
    'darkviolet',
    'deeppink',
    'deepskyblue',
    'dimgray',
    'dimgrey',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'gold',
    'goldenrod',
    'gray',
    'green',
    'greenyellow',
    'grey',
    'honeydew',
    'hotpink',
    'indianred',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavenderblush',
    'lawngreen',
    'lemonchiffon',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'lightgray',
    'lightgreen',
    'lightgrey',
    'lightpink',
    'lightsalmon',
    'lightseagreen',
    'lightskyblue',
    'lightslategray',
    'lightslategrey',
    'lightsteelblue',
    'lightyellow',
    'lime',
    'limegreen',
    'linen',
    'magenta',
    'maroon',
    'mediumaquamarine',
    'mediumblue',
    'mediumorchid',
    'mediumpurple',
    'mediumseagreen',
    'mediumslateblue',
    'mediumspringgreen',
    'mediumturquoise',
    'mediumvioletred',
    'midnightblue',
    'mintcream',
    'mistyrose',
    'moccasin',
    'navajowhite',
    'navy',
    'oldlace',
    'olive',
    'olivedrab',
    'orange',
    'orangered',
    'orchid',
    'palegoldenrod',
    'palegreen',
    'paleturquoise',
    'palevioletred',
    'papayawhip',
    'peachpuff',
    'peru',
    'pink',
    'plum',
    'powderblue',
    'purple',
    'rebeccapurple',
    'red',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'salmon',
    'sandybrown',
    'seagreen',
    'seashell',
    'sienna',
    'silver',
    'skyblue',
    'slateblue',
    'slategray',
    'slategrey',
    'snow',
    'springgreen',
    'steelblue',
    'tan',
    'teal',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'white',
    'whitesmoke',
    'yellow',
    'yellowgreen',
]

/**
 * @see {@link https://drafts.csswg.org/css-color-4/#typedef-system-color}
 */
const system = [
    'AccentColor',
    'AccentColorText',
    'ActiveText',
    'ButtonBorder',
    'ButtonFace',
    'ButtonText',
    'Canvas',
    'CanvasText',
    'Field',
    'FieldText',
    'GrayText',
    'Highlight',
    'HighlightText',
    'LinkText',
    'Mark',
    'MarkText',
    'SelectedItem',
    'SelectedItemText',
    'VisitedText',
]

module.exports = {
    colorFunctionKeywords,
    colorSpaceKeywords,
    colorSpaces,
    deprecated: deprecated.map(([mapped]) => mapped),
    named,
    system,
}
