
import { ident, keyword, length, list, number, omitted } from './value.js'

export const auto = keyword('auto')
export const collapse = keyword('collapse')
export const column = keyword('column')
export const justify = keyword('justify')
export const noAutospace = keyword('no-autospace')
export const noRepeat = keyword('no-repeat', ['<repeat-style>'])
export const none = keyword('none')
export const notAll = list([ident('not'), ident('all', ['<media-type>']), omitted], ' ', ['<media-query>'])
export const one = number(1)
export const repeat = keyword('repeat', ['<repetition>'])
export const row = keyword('row')
export const spaceAll = keyword('space-all', ['<spacing-trim>'])
export const spacingTrim = list([omitted, keyword('space-first')], ' ', ['<spacing-trim>'])
export const start = keyword('start')
export const transparent = keyword('transparent')
export const webkitLegacy = keyword('-webkit-legacy')
export const zero = number(0)
export const zeroPx = length(0, 'px')
